name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Github pages
      run: |
        yarn
        yarn build
        git config --global user.email "matheusfreirerabelo@gmail.com"
        git config --global user.name "Matheus Rabelo"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/matheusrabelo/dream-trip
        git add -f static
        git commit -am "Automated deploy"
        git subtree split --prefix static -b gh-pages
        git push -f origin gh-pages

    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
